name: 'Terraform'

on:
  push:
    branches:
    - master
  pull_request:
    
defaults:
  run:
    working-directory: VM-Terrform

jobs:
  terraform:
    name: 'Terrform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Terraform security scan
      uses: triat/terraform-security-scan@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
